const { test, expect } = require('@playwright/test');
const path = require('path');

async function ensureLoggedIn(page) {
    await page.goto('/landing');
    // Check if we are already logged in (user menu toggle exists)
    const isLoggedOut = await page.locator('button[data-modal="login"]').isVisible();
    if (isLoggedOut) {
        await page.click('button[data-modal="login"]');
        await expect(page.locator('#authModal')).toBeVisible();
        await page.fill('#login-username', 'admin');
        await page.fill('#login-password', 'Admin@123');
        await page.click('.btn-signin-blue');
        await page.waitForTimeout(2000); // Wait for redirect/animation
        // Admin redirects to /admin
        await expect(page).toHaveURL(/\/admin/);
    } else {
        // If already logged in, ensure we are on a page where we can navigate
        const url = page.url();
        if (url.includes('/landing')) {
             await page.goto('/admin');
        }
    }
}

test.describe('News-Slyzer Comprehensive Test Suite', () => {

    test('1. Verify Homepage Loads Successfully', async ({ page }) => {
        await page.goto('/');
        // If not logged in, it redirects to /landing
        if (page.url().includes('/landing')) {
            await expect(page.locator('.news-portal-title')).toBeVisible();
        } else {
            // If logged in as admin, it redirects to /admin
            await expect(page).toHaveURL(/\/(admin)?/);
        }
    });

    test('2. Test Login with Valid and Invalid Credentials', async ({ page }) => {
        await page.goto('/logout'); 
        await page.goto('/landing');
        
        // --- Invalid Credentials ---
        const loginBtn = page.locator('button[data-modal="login"]');
        await expect(loginBtn).toBeVisible();
        await loginBtn.click();
        
        await expect(page.locator('#authModal')).toBeVisible();
        await page.fill('#login-username', 'invalid_user');
        await page.fill('#login-password', 'InvalidPass123!');
        await page.click('.btn-signin-blue');
        
        await expect(page.locator('.alert-danger')).toBeVisible();

        // --- Valid Credentials ---
        await page.fill('#login-username', 'admin');
        await page.fill('#login-password', 'Admin@123');
        await page.click('.btn-signin-blue');
        await page.waitForTimeout(2000); // Wait for redirect/animation

        // Should redirect to admin dashboard
        await expect(page).toHaveURL(/\/admin/);
        await expect(page.locator('#userMenuToggle')).toBeVisible();
    });

    test('3. Test Logout Functionality', async ({ page }) => {
        await ensureLoggedIn(page);
        
        await page.click('#userMenuToggle');
        await expect(page.locator('#userMenu')).toBeVisible();
        await page.click('a[href="/logout"]');

        await expect(page.url()).toContain('/landing');
        await expect(page.locator('button[data-modal="login"]')).toBeVisible();
    });

    test('4. Test Local News Submission Form', async ({ page }) => {
        await ensureLoggedIn(page);

        await page.goto('/submit-local-news');
        await page.fill('#title', 'Playwright Automated Test Incident');
        await page.selectOption('#category', 'Community');
        await page.fill('#location', 'Test City');
        
        await page.evaluate(() => {
            const lat = document.getElementById('latitude');
            const lon = document.getElementById('longitude');
            if (lat) lat.value = '10.0';
            if (lon) lon.value = '76.0';
        });

        await page.fill('#incident_date', '2026-03-20T10:00');
        await page.fill('#content', 'This is a test submission generated by Playwright to verify the local news submission workflow.');

        await page.click('button.submit-btn');
        await expect(page.locator('.alert-success')).toBeVisible();
    });

    test('5. Test Advertisement Posting Feature', async ({ page }) => {
        await page.goto('/advertise');
        
        await page.click('text=Select Plan >> nth=0'); 

        await expect(page.locator('#step-placement')).toBeVisible();
        await page.click('text=Header Banner');
        await page.click('text=Continue to Details');

        await expect(page.locator('#step-details')).toBeVisible();
        await page.fill('input[name="company_name"]', 'Playwright Ads');
        await page.fill('input[name="title"]', 'Automated Ad Title');
        await page.fill('input[name="contact_email"]', 'ads@test.com');
        
        const fileChooserPromise = page.waitForEvent('filechooser');
        const uploadWrapper = page.locator('.file-upload-wrapper');
        await uploadWrapper.scrollIntoViewIfNeeded();
        await uploadWrapper.click();
        const fileChooser = await fileChooserPromise;
        await fileChooser.setFiles(path.join(__dirname, 'dummy_ad.png'));
        
        await page.click('button[type="submit"]');
        await expect(page).toHaveURL(/\/payment\//);
    });

    test('6. Test Category-based News Filtering', async ({ page }) => {
        await ensureLoggedIn(page);
        
        // Admin dashboard doesn't have the category nav, so we go to a news category page directly
        await page.goto('/category/sports');
        
        await expect(page).toHaveURL(/\/category\/sports/i);
        await expect(page.locator('.page-title')).toContainText('sports', { ignoreCase: true });
        
        const newsItems = page.locator('.news-card');
        await expect(newsItems.first()).toBeVisible();
    });

    test('7. Test Malayalam ↔ English Language Toggle', async ({ page }) => {
        await page.goto('/landing');
        
        const initialLang = await page.getAttribute('html', 'lang');
        const toggleBtn = page.locator('.btn-lang-toggle');
        
        await toggleBtn.click();
        
        const newLang = await page.getAttribute('html', 'lang');
        expect(newLang).not.toBe(initialLang);
        
        if (newLang === 'ml') {
            await expect(toggleBtn).toContainText('ENGLISH');
        } else {
            await expect(toggleBtn).toContainText('MALAYALAM');
        }
        
        await toggleBtn.click();
        const backToInitial = await page.getAttribute('html', 'lang');
        expect(backToInitial).toBe(initialLang);
    });

});
