const { test, expect } = require('@playwright/test');
const path = require('path');

test.describe('Reporter Workflow Tests', () => {
    test('Submit News Story', async ({ page }) => {
        // Login as reporter
        await page.goto('/');
        await page.click('button[data-modal="login"]');
        await page.fill('#login-username', 'reporter');
        await page.fill('#login-password', 'Reporter@123');
        await page.click('#loginForm button[type="submit"]');
        await expect(page).toHaveURL(/\/reporter/);

        // Navigate to Submit News
        await page.click('a:has-text("Create New Article")');
        await expect(page).toHaveURL(/\/submit-news/);
        await expect(page.locator('h1')).toContainText('Submit Local News');

        // Fill form
        const testTitle = `Automated Test News ${Date.now()}`;
        await page.fill('input[name="title"]', testTitle);
        await page.selectOption('select[name="category"]', 'Technology');
        await page.fill('textarea[name="content"]', 'This is a test article content generated by Playwright automation for JANAVAAKYA – Voice of the People project-wide verification.');

        // Upload a cover image (required by form)
        await page.setInputFiles('input[name="image"]', path.join(__dirname, '../static/img/economy.jpg'));

        // Submit the form
        await page.click('button[type="submit"]');

        // Verify success flash and redirection
        await expect(page).toHaveURL(/\/$/); // Redirects to home
        await expect(page.locator('.alert-success, .flash-success').first()).toBeVisible();

        // Verify the new article appears in the feed
        await expect(page.locator('.news-card').first()).toContainText(testTitle);
    });
});
